project_id = "jywwgoceybjendvpbqea"

[auth]
site_url = "http://localhost:8080"
additional_redirect_urls = ["http://localhost:8080/**"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false
minimum_password_length = 8
password_requirements = ""

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = true
max_frequency = "1m"

[storage]
enabled = true
file_size_limit = "50MiB"

[storage.buckets.school-assets]
public = false
file_size_limit = "10MiB"
allowed_mime_types = ["image/png", "image/jpeg", "image/webp", "image/svg+xml"]
