/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CreateOrganizationRouteImport } from './routes/create-organization'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WelcomeIndexRouteImport } from './routes/welcome.index'
import { Route as WelcomeCreateRouteImport } from './routes/welcome.create'
import { Route as LookupQrTokenRouteImport } from './routes/lookup.$qrToken'
import { Route as KioskTokenRouteImport } from './routes/kiosk.$token'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppTeachersRouteImport } from './routes/_authenticated/app.teachers'
import { Route as AuthenticatedAppStudentsRouteImport } from './routes/_authenticated/app.students'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppReportsRouteImport } from './routes/_authenticated/app.reports'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated/app.onboarding'
import { Route as AuthenticatedAppImportRouteImport } from './routes/_authenticated/app.import'
import { Route as AuthenticatedAppClassesRouteImport } from './routes/_authenticated/app.classes'
import { Route as AuthenticatedAppInviteTokenRouteImport } from './routes/_authenticated/app.invite.$token'
import { Route as AuthenticatedAppClassesClassIdRouteImport } from './routes/_authenticated/app.classes.$classId'
import { Route as AuthenticatedAppClassesClassIdQrRouteImport } from './routes/_authenticated/app.classes.$classId.qr'

const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeIndexRoute = WelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeCreateRoute = WelcomeCreateRouteImport.update({
  id: '/welcome/create',
  path: '/welcome/create',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupQrTokenRoute = LookupQrTokenRouteImport.update({
  id: '/lookup/$qrToken',
  path: '/lookup/$qrToken',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskTokenRoute = KioskTokenRouteImport.update({
  id: '/kiosk/$token',
  path: '/kiosk/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTeachersRoute =
  AuthenticatedAppTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppStudentsRoute =
  AuthenticatedAppStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppReportsRoute = AuthenticatedAppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppImportRoute = AuthenticatedAppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClassesRoute = AuthenticatedAppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppInviteTokenRoute =
  AuthenticatedAppInviteTokenRouteImport.update({
    id: '/invite/$token',
    path: '/invite/$token',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppClassesClassIdRoute =
  AuthenticatedAppClassesClassIdRouteImport.update({
    id: '/$classId',
    path: '/$classId',
    getParentRoute: () => AuthenticatedAppClassesRoute,
  } as any)
const AuthenticatedAppClassesClassIdQrRoute =
  AuthenticatedAppClassesClassIdQrRouteImport.update({
    id: '/qr',
    path: '/qr',
    getParentRoute: () => AuthenticatedAppClassesClassIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/demo': typeof DemoRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/kiosk/$token': typeof KioskTokenRoute
  '/lookup/$qrToken': typeof LookupQrTokenRoute
  '/welcome/create': typeof WelcomeCreateRoute
  '/welcome/': typeof WelcomeIndexRoute
  '/app/classes': typeof AuthenticatedAppClassesRouteWithChildren
  '/app/import': typeof AuthenticatedAppImportRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/students': typeof AuthenticatedAppStudentsRoute
  '/app/teachers': typeof AuthenticatedAppTeachersRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/classes/$classId': typeof AuthenticatedAppClassesClassIdRouteWithChildren
  '/app/invite/$token': typeof AuthenticatedAppInviteTokenRoute
  '/app/classes/$classId/qr': typeof AuthenticatedAppClassesClassIdQrRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/demo': typeof DemoRoute
  '/kiosk/$token': typeof KioskTokenRoute
  '/lookup/$qrToken': typeof LookupQrTokenRoute
  '/welcome/create': typeof WelcomeCreateRoute
  '/welcome': typeof WelcomeIndexRoute
  '/app/classes': typeof AuthenticatedAppClassesRouteWithChildren
  '/app/import': typeof AuthenticatedAppImportRoute
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/reports': typeof AuthenticatedAppReportsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/students': typeof AuthenticatedAppStudentsRoute
  '/app/teachers': typeof AuthenticatedAppTeachersRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/classes/$classId': typeof AuthenticatedAppClassesClassIdRouteWithChildren
  '/app/invite/$token': typeof AuthenticatedAppInviteTokenRoute
  '/app/classes/$classId/qr': typeof AuthenticatedAppClassesClassIdQrRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/demo': typeof DemoRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/kiosk/$token': typeof KioskTokenRoute
  '/lookup/$qrToken': typeof LookupQrTokenRoute
  '/welcome/create': typeof WelcomeCreateRoute
  '/welcome/': typeof WelcomeIndexRoute
  '/_authenticated/app/classes': typeof AuthenticatedAppClassesRouteWithChildren
  '/_authenticated/app/import': typeof AuthenticatedAppImportRoute
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/reports': typeof AuthenticatedAppReportsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/students': typeof AuthenticatedAppStudentsRoute
  '/_authenticated/app/teachers': typeof AuthenticatedAppTeachersRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/classes/$classId': typeof AuthenticatedAppClassesClassIdRouteWithChildren
  '/_authenticated/app/invite/$token': typeof AuthenticatedAppInviteTokenRoute
  '/_authenticated/app/classes/$classId/qr': typeof AuthenticatedAppClassesClassIdQrRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/create-organization'
    | '/demo'
    | '/app'
    | '/kiosk/$token'
    | '/lookup/$qrToken'
    | '/welcome/create'
    | '/welcome/'
    | '/app/classes'
    | '/app/import'
    | '/app/onboarding'
    | '/app/reports'
    | '/app/settings'
    | '/app/students'
    | '/app/teachers'
    | '/app/'
    | '/app/classes/$classId'
    | '/app/invite/$token'
    | '/app/classes/$classId/qr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/create-organization'
    | '/demo'
    | '/kiosk/$token'
    | '/lookup/$qrToken'
    | '/welcome/create'
    | '/welcome'
    | '/app/classes'
    | '/app/import'
    | '/app/onboarding'
    | '/app/reports'
    | '/app/settings'
    | '/app/students'
    | '/app/teachers'
    | '/app'
    | '/app/classes/$classId'
    | '/app/invite/$token'
    | '/app/classes/$classId/qr'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/create-organization'
    | '/demo'
    | '/_authenticated/app'
    | '/kiosk/$token'
    | '/lookup/$qrToken'
    | '/welcome/create'
    | '/welcome/'
    | '/_authenticated/app/classes'
    | '/_authenticated/app/import'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/reports'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/students'
    | '/_authenticated/app/teachers'
    | '/_authenticated/app/'
    | '/_authenticated/app/classes/$classId'
    | '/_authenticated/app/invite/$token'
    | '/_authenticated/app/classes/$classId/qr'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  DemoRoute: typeof DemoRoute
  KioskTokenRoute: typeof KioskTokenRoute
  LookupQrTokenRoute: typeof LookupQrTokenRoute
  WelcomeCreateRoute: typeof WelcomeCreateRoute
  WelcomeIndexRoute: typeof WelcomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/': {
      id: '/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof WelcomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome/create': {
      id: '/welcome/create'
      path: '/welcome/create'
      fullPath: '/welcome/create'
      preLoaderRoute: typeof WelcomeCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup/$qrToken': {
      id: '/lookup/$qrToken'
      path: '/lookup/$qrToken'
      fullPath: '/lookup/$qrToken'
      preLoaderRoute: typeof LookupQrTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk/$token': {
      id: '/kiosk/$token'
      path: '/kiosk/$token'
      fullPath: '/kiosk/$token'
      preLoaderRoute: typeof KioskTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/teachers': {
      id: '/_authenticated/app/teachers'
      path: '/teachers'
      fullPath: '/app/teachers'
      preLoaderRoute: typeof AuthenticatedAppTeachersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/students': {
      id: '/_authenticated/app/students'
      path: '/students'
      fullPath: '/app/students'
      preLoaderRoute: typeof AuthenticatedAppStudentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/reports': {
      id: '/_authenticated/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AuthenticatedAppReportsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/import': {
      id: '/_authenticated/app/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AuthenticatedAppImportRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/classes': {
      id: '/_authenticated/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AuthenticatedAppClassesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/invite/$token': {
      id: '/_authenticated/app/invite/$token'
      path: '/invite/$token'
      fullPath: '/app/invite/$token'
      preLoaderRoute: typeof AuthenticatedAppInviteTokenRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/classes/$classId': {
      id: '/_authenticated/app/classes/$classId'
      path: '/$classId'
      fullPath: '/app/classes/$classId'
      preLoaderRoute: typeof AuthenticatedAppClassesClassIdRouteImport
      parentRoute: typeof AuthenticatedAppClassesRoute
    }
    '/_authenticated/app/classes/$classId/qr': {
      id: '/_authenticated/app/classes/$classId/qr'
      path: '/qr'
      fullPath: '/app/classes/$classId/qr'
      preLoaderRoute: typeof AuthenticatedAppClassesClassIdQrRouteImport
      parentRoute: typeof AuthenticatedAppClassesClassIdRoute
    }
  }
}

interface AuthenticatedAppClassesClassIdRouteChildren {
  AuthenticatedAppClassesClassIdQrRoute: typeof AuthenticatedAppClassesClassIdQrRoute
}

const AuthenticatedAppClassesClassIdRouteChildren: AuthenticatedAppClassesClassIdRouteChildren =
  {
    AuthenticatedAppClassesClassIdQrRoute:
      AuthenticatedAppClassesClassIdQrRoute,
  }

const AuthenticatedAppClassesClassIdRouteWithChildren =
  AuthenticatedAppClassesClassIdRoute._addFileChildren(
    AuthenticatedAppClassesClassIdRouteChildren,
  )

interface AuthenticatedAppClassesRouteChildren {
  AuthenticatedAppClassesClassIdRoute: typeof AuthenticatedAppClassesClassIdRouteWithChildren
}

const AuthenticatedAppClassesRouteChildren: AuthenticatedAppClassesRouteChildren =
  {
    AuthenticatedAppClassesClassIdRoute:
      AuthenticatedAppClassesClassIdRouteWithChildren,
  }

const AuthenticatedAppClassesRouteWithChildren =
  AuthenticatedAppClassesRoute._addFileChildren(
    AuthenticatedAppClassesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppClassesRoute: typeof AuthenticatedAppClassesRouteWithChildren
  AuthenticatedAppImportRoute: typeof AuthenticatedAppImportRoute
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppReportsRoute: typeof AuthenticatedAppReportsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppStudentsRoute: typeof AuthenticatedAppStudentsRoute
  AuthenticatedAppTeachersRoute: typeof AuthenticatedAppTeachersRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppInviteTokenRoute: typeof AuthenticatedAppInviteTokenRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppClassesRoute: AuthenticatedAppClassesRouteWithChildren,
  AuthenticatedAppImportRoute: AuthenticatedAppImportRoute,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppReportsRoute: AuthenticatedAppReportsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppStudentsRoute: AuthenticatedAppStudentsRoute,
  AuthenticatedAppTeachersRoute: AuthenticatedAppTeachersRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppInviteTokenRoute: AuthenticatedAppInviteTokenRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CreateOrganizationRoute: CreateOrganizationRoute,
  DemoRoute: DemoRoute,
  KioskTokenRoute: KioskTokenRoute,
  LookupQrTokenRoute: LookupQrTokenRoute,
  WelcomeCreateRoute: WelcomeCreateRoute,
  WelcomeIndexRoute: WelcomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
